### ISSUE TITLE
Updating model from controller does not update control

### ISSUE THREAD

**Issue by jeffreyramia** [jkuri/ngTimepicker#2]
$scope.time = '12:00';

Does not cause the control to update. Seems it's one-way binding.

Is there are fix for this?

Thanks

**Comment by jeffreyramia** [comment]
Fixed using this code:

```
               scope.$watch(attrs['ngModel'], function (newTime) {
                    scope.initTime = newTime;
                    reinitTime();
                });
```

**Comment by jkuri** [comment]
Glad you solved it, perhaps `ngModel.$render = function () ...` would be better, I think.
