### ISSUE TITLE
Update code: issue #2 Updating model from controller does not update control

### ISSUE THREAD

**Issue by elineopsommer** [jkuri/ngTimepicker#3]
Can you take this solution along in your code? Thanks

scope.$watch(attrs['ngModel'], function (newTime) {
                    scope.initTime = newTime;
                    reinitTime();
                });

**Comment by christianleypoldt** [comment]
Spot on! This fix was exactly what i was looking for.

**Comment by jkuri** [comment]
Can someone make a PR please?

**Comment by elineopsommer** [comment]
I had already made a PR: https://github.com/jkuri/ngTimepicker/pull/4

**Comment by jkuri** [comment]
Sorry, I missed it. Thanks for your PR, it's merged.
